import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  team,
  analytics,
}: Readonly<{
  children: React.ReactNode
  team: React.ReactNode
  analytics: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AntdRegistry>
          <div className='container mx-auto'>
            <div className='flex justify-center text-blue-500 p-6 gap-6'>
              <Link href='/'>首页</Link>
              <Link href='/vistors'>访客</Link>
            </div>
            <div className='flex gap-6'>
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
